/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expenseManage;

/**
 *
 * @author User-PC
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        UserLabel = new javax.swing.JLabel();
        BalanceName = new javax.swing.JLabel();
        BalanceQuantity = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        BalanceBar = new javax.swing.JProgressBar();
        BalanceBarLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Date = new javax.swing.JTextField();
        Day = new javax.swing.JTextField();
        Month = new javax.swing.JTextField();
        BalanceBarSpent = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 769));
        setMinimumSize(new java.awt.Dimension(450, 769));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(466, 769));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(226, 255, 223));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        UserLabel.setText("Hi, User1234");
        jPanel2.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 34, -1, -1));

        BalanceName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BalanceName.setText("Balance");
        jPanel2.add(BalanceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        BalanceQuantity.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        BalanceQuantity.setText("P251.99");
        jPanel2.add(BalanceQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 111, -1, 43));

        jPanel4.setBackground(new java.awt.Color(226, 255, 223));

        BalanceBar.setBackground(new java.awt.Color(255, 255, 255));
        BalanceBar.setToolTipText("");
        BalanceBar.setValue(30);
        BalanceBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        BalanceBar.setOpaque(true);

        BalanceBarLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BalanceBarLabel.setText("25%");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BalanceBarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BalanceBar, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BalanceBarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(BalanceBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 178, 417, -1));

        jPanel3.setBackground(new java.awt.Color(226, 255, 223));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Date.setEditable(false);
        Date.setBackground(new java.awt.Color(174, 253, 163));
        Date.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        Date.setForeground(new java.awt.Color(28, 108, 30));
        Date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Date.setText("01");
        Date.setFocusable(false);
        Date.setMaximumSize(new java.awt.Dimension(104, 79));
        Date.setMinimumSize(new java.awt.Dimension(104, 79));
        Date.setPreferredSize(new java.awt.Dimension(104, 79));
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        jPanel3.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 60));

        Day.setEditable(false);
        Day.setBackground(new java.awt.Color(0, 102, 0));
        Day.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        Day.setForeground(new java.awt.Color(255, 255, 255));
        Day.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Day.setText("Tuesday");
        Day.setFocusable(false);
        Day.setMinimumSize(new java.awt.Dimension(104, 37));
        Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayActionPerformed(evt);
            }
        });
        jPanel3.add(Day, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, 30));

        Month.setEditable(false);
        Month.setBackground(new java.awt.Color(87, 184, 91));
        Month.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Month.setForeground(new java.awt.Color(255, 255, 255));
        Month.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Month.setText("January");
        Month.setFocusable(false);
        Month.setMaximumSize(new java.awt.Dimension(104, 37));
        Month.setMinimumSize(new java.awt.Dimension(104, 37));
        Month.setPreferredSize(new java.awt.Dimension(104, 37));
        Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthActionPerformed(evt);
            }
        });
        jPanel3.add(Month, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 28, 101, -1));

        BalanceBarSpent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BalanceBarSpent.setText("P749.99");
        jPanel2.add(BalanceBarSpent, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 214, -1, -1));

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MonthActionPerformed

    private void DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        com.formdev.flatlaf.FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BalanceBar;
    private javax.swing.JLabel BalanceBarLabel;
    private javax.swing.JLabel BalanceBarSpent;
    private javax.swing.JLabel BalanceName;
    private javax.swing.JLabel BalanceQuantity;
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Day;
    private javax.swing.JTextField Month;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
